version: '3'

services:
  redis:
    container_name: 'redis-container'
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # command: redis-server --requirepass redis2022 --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/ngel/Redis:/var/lib/postgresql/data
